// <auto-generated />
namespace AlfaBank.AlfaCollection.Services.PersonService.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v005 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v005));
        
        string IMigrationMetadata.Id
        {
            get { return "201704271233322_v0.05"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
