// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace CollateralService.ApiClient.Client.Models.Presentation.Responses.Collateral
{
    using CollateralService.ApiClient;
    using CollateralService.ApiClient.Client;
    using Newtonsoft.Json;
    using System;
    using System.Linq;

    public partial class CollateralAgreement
    {
        /// <summary>
        /// Initializes a new instance of the
        /// BusinessLayerModelsPresentationResponsesCollateralAgreementCollateralAgreement
        /// class.
        /// </summary>
        public CollateralAgreement()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// BusinessLayerModelsPresentationResponsesCollateralAgreementCollateralAgreement
        /// class.
        /// </summary>
        public CollateralAgreement(
            string id = default(string), 
            string number = default(string),
            DateTime openDate = default(DateTime),
            DateTime closeDate = default(DateTime),
            string personId = default(string)
        )
        {
            Id = id;
            Number = number;
            OpenDate = openDate;
            CloseDate = closeDate;
            PersonId = personId;

            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Number")]
        public string Number { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OpenDate")]
        public DateTime? OpenDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CloseDate")]
        public DateTime? CloseDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PersonId")]
        public string PersonId { get; set; }
    }
}
