// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace CollateralService.ApiClient.Client
{
    using CollateralService.ApiClient;
    using Microsoft.Rest;
    using Models;
    using Newtonsoft.Json;

    /// <summary>
    /// </summary>
    public partial interface ICollateralServiceWebAPI : System.IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        System.Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }

        /// <summary>
        /// Subscription credentials which uniquely identify client
        /// subscription.
        /// </summary>
        ServiceClientCredentials Credentials { get; }


        /// <summary>
        /// Gets the ICollateral.
        /// </summary>
        ICollateral Collateral { get; }

        /// <summary>
        /// Gets the ICollateralAgreements.
        /// </summary>
        ICollateralAgreements CollateralAgreements { get; }

        /// <summary>
        /// Gets the ICreditAgreement.
        /// </summary>
        ICreditAgreement CreditAgreement { get; }

    }
}
